backend:
  name: github
  repo: tunan-pan/tunan-pan.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  client_id: Ov23lipGxkU9JVjVWRJ8

media_folder: "/images/uploads" # where uploaded images go
public_folder: "/images/uploads" # URL path for images

collections:
  - name: "projects"        # Used in admin URLs
    label: "Projects"       # Used in the UI
    folder: "/projects"  # Where your project markdown files are
    create: true            # Allow users to create new projects
    slug: "{{slug}}"        # Filename template
    fields:                 # The fields for each project
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
